module.exports={
    routes:[
        {
            method:'GET',
            path:'/pages/:Path',
            handler:'page.findOne',
            config:{
                auth:false,
            }
        }
    ]
}